### ISSUE TITLE
active model serializer gem issues

### ISSUE THREAD

**Issue by viparthasarathy** [learn-co-students/using-active-model-serializer-lab-v-000#42] opened 2016-06-01 23:37 UTC
The labs test specs and solution seem to be built under the assumption that ActiveModelSerializer 0.9.x is being used, but the master branch doesn't include the gem in the gemfile. As a result, when I added the gem to my gemfile it installed 0.10.x, which results in a different serialization format. Notably, the product information is no longer nested inside data and the has_many products relationship doesn't show up for orders when nested within products.

Using 0.9.4:
![screen shot 2016-06-01 at 4 26 15 pm](https://cloud.githubusercontent.com/assets/9505145/15729091/f42480d2-2815-11e6-95f8-25a2d143de4b.png)

Using 0.10.0:
![screen shot 2016-06-01 at 4 28 26 pm](https://cloud.githubusercontent.com/assets/9505145/15729095/fa8e0be6-2815-11e6-91c8-6bec44374ab9.png)

The work around that I used to maintain the has_many products relationship for orders while using 0.10.0 is to specify :products as an attribute in the Order serializer, but I'm not sure that's ideal as it reveals all of the attributes specified in the Product serializer save for the has_many orders relationship:

![screen shot 2016-06-01 at 4 33 43 pm](https://cloud.githubusercontent.com/assets/9505145/15729177/a38968e4-2816-11e6-9c79-36b692bff739.png)

**Comment by the-widget** [comment] 2016-06-02 15:41
Thanks for posting this detailed issue. I also went through the same process.

**Comment by thebrianemory** [comment] 2016-07-16 19:24
Thanks for this. I was wondering why I couldn't get it to list the name without using :products. Using `gem "active_model_serializers", "~> 0.9.0"` will get the intended behavior.

**Comment by viparthasarathy** [comment] 2016-07-16 19:47
No worries. This one was pretty annoying on my end too. Hope they fix it soon.

**Comment by michaelsimon** [comment] 2016-09-01 01:25
+1

**Comment by gj** [comment] 2016-10-05 19:21
cc: @mendelB

**Comment by mdo5004** [comment] 2017-05-22 14:48
+1 This is still an issue. 

With AMS ~>0.9.0 specified in my Gemfile, I had to add 
```
body = body["product"]
```
to line 28 of `products_controller_spec.rb` to get it to access the `product` object.

**Comment by mdo5004** [comment] 2017-05-22 14:57
@aturkewi You seem to be the person to tag.

**Comment by mdo5004** [comment] 2017-05-22 15:01
@cernanb

**Comment by aturkewi** [comment] 2017-05-22 15:34
Hey all! Thanks so much for raising and tracking this issue :) It is much appreciated.
I just re-raised the issue at https://github.com/learn-co-curriculum/using-active-model-serializer-lab/issues/8 

A quick note on raising issues on Learn curriculum. First off, it's always helpful and appreciated even if we cannot immediately get to it (so thanks again!). All of our issues and PRs to curriculum though are tracked on the `learn-co-curriculum` org and _not_ the `learn-co-students` org. The `learn-co-curriculum` org holds the master copy, while this is simply a deploy of the lab. You'll notice this lab has close to 200 PRs, it would be hard to find a _real_ change to the lesson there. We also have different deploys for different groups (the online course is `v-000` but we may need the same lab in bootcamp prep for example `bootcamp-prep-000`). You an always find the master version of the lab by clicking the button in Learn to raise an issue :)

So I'm going to close this out, but we are continuing to track it on the link posted above!

**Closed by aturkewi** 2017-05-22 15:34 UTC
